plugins {
    id 'com.android.application'
}

apply from: '../gradle/license-html-generator.gradle'

def keyStoreFile = null
if (System.getenv("SIGNING_KEY") != null) {
    println 'key exist'
    keyStoreFile = File.createTempFile("key", null)
    keyStoreFile.deleteOnExit()
    keyStoreFile.bytes = Base64.decoder.decode(System.getenv("SIGNING_KEY"))
} else {
    println 'key NOT exist'
}

android {
    compileSdk = 37

    signingConfigs {
        release {
            storeFile keyStoreFile
            storePassword System.getenv("KEY_STORE_PASSWORD")
            keyAlias System.getenv("ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }
    defaultConfig {
        applicationId "m.co.rh.id.a_medic_log"
        minSdk 21
        targetSdk 37
        versionCode 29
        versionName "2.1.0"
        vectorDrawables.useSupportLibrary true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("SIGNING_KEY") != null) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'm.co.rh.id.a_medic_log'
    packaging {
        resources {
            pickFirsts += 'META-INF/DEPENDENCIES'
        }
    }
    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation project(path: ':base')

    implementation libs.a.poi.spreadsheet

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.drawerlayout
    implementation libs.androidx.recyclerview
    implementation libs.androidx.gridlayout
    implementation libs.androidx.swiperefreshlayout
    implementation libs.photoview

    implementation libs.work.runtime
    implementation libs.leakcanary.plumber

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.work.testing
}

project.afterEvaluate {
    def versionCode = android.defaultConfig.versionCode
    File changeLogTxt = new File(project.rootDir, "fastlane/metadata/android/en-US/changelogs/" + versionCode + ".txt")
    if (changeLogTxt.exists()) {
        File outputChangeLog = new File(project.layout.buildDirectory.get().asFile, "changelog.txt")
        if (!outputChangeLog.exists()) {
            outputChangeLog.parentFile.mkdirs()
            outputChangeLog.createNewFile()
        }
        outputChangeLog.bytes = changeLogTxt.bytes
    }
}